# TCL File Generated by Component Editor 18.1
# Sun May 05 19:17:57 IST 2024
# DO NOT MODIFY


# 
# madgwick_filter "Madgwick Filter" v1.0
#  2024.05.05.19:17:57
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module madgwick_filter
# 
set_module_property DESCRIPTION ""
set_module_property NAME madgwick_filter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP My_IP
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Madgwick Filter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL filter_avalon_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Prop_gen.v VERILOG PATH Prop_gen.v
add_fileset_file abs26.v VERILOG PATH abs26.v
add_fileset_file class.v VERILOG PATH class.v
add_fileset_file filter.v VERILOG PATH filter.v
add_fileset_file flags.vh OTHER PATH flags.vh
add_fileset_file fp_as.v VERILOG PATH fp_as.v
add_fileset_file fp_div.v VERILOG PATH fp_div.v
add_fileset_file fp_mul.v VERILOG PATH fp_mul.v
add_fileset_file prefix_adder.v VERILOG PATH prefix_adder.v
add_fileset_file quaternion_lib.v VERILOG PATH quaternion_lib.v
add_fileset_file filter_avalon_interface.v VERILOG PATH filter_avalon_interface.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL filter_avalon_interface
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Prop_gen.v VERILOG PATH Prop_gen.v
add_fileset_file abs26.v VERILOG PATH abs26.v
add_fileset_file class.v VERILOG PATH class.v
add_fileset_file filter.v VERILOG PATH filter.v
add_fileset_file flags.vh OTHER PATH flags.vh
add_fileset_file fp_as.v VERILOG PATH fp_as.v
add_fileset_file fp_div.v VERILOG PATH fp_div.v
add_fileset_file fp_mul.v VERILOG PATH fp_mul.v
add_fileset_file prefix_adder.v VERILOG PATH prefix_adder.v
add_fileset_file quaternion_lib.v VERILOG PATH quaternion_lib.v
add_fileset_file filter_avalon_interface.v VERILOG PATH filter_avalon_interface.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink resetn reset_n Input 1


# 
# connection point filter_alu_slave
# 
add_interface filter_alu_slave avalon end
set_interface_property filter_alu_slave addressUnits WORDS
set_interface_property filter_alu_slave associatedClock clock
set_interface_property filter_alu_slave associatedReset reset_sink
set_interface_property filter_alu_slave bitsPerSymbol 8
set_interface_property filter_alu_slave burstOnBurstBoundariesOnly false
set_interface_property filter_alu_slave burstcountUnits WORDS
set_interface_property filter_alu_slave explicitAddressSpan 0
set_interface_property filter_alu_slave holdTime 0
set_interface_property filter_alu_slave linewrapBursts false
set_interface_property filter_alu_slave maximumPendingReadTransactions 0
set_interface_property filter_alu_slave maximumPendingWriteTransactions 0
set_interface_property filter_alu_slave readLatency 0
set_interface_property filter_alu_slave readWaitTime 1
set_interface_property filter_alu_slave setupTime 0
set_interface_property filter_alu_slave timingUnits Cycles
set_interface_property filter_alu_slave writeWaitTime 0
set_interface_property filter_alu_slave ENABLED true
set_interface_property filter_alu_slave EXPORT_OF ""
set_interface_property filter_alu_slave PORT_NAME_MAP ""
set_interface_property filter_alu_slave CMSIS_SVD_VARIABLES ""
set_interface_property filter_alu_slave SVD_ADDRESS_GROUP ""

add_interface_port filter_alu_slave write write Input 1
add_interface_port filter_alu_slave read read Input 1
add_interface_port filter_alu_slave byteenable byteenable Input 4
add_interface_port filter_alu_slave chipselect chipselect Input 1
add_interface_port filter_alu_slave slave_address address Input 16
add_interface_port filter_alu_slave slave_readdata readdata Output 32
add_interface_port filter_alu_slave slave_writedata writedata Input 32
set_interface_assignment filter_alu_slave embeddedsw.configuration.isFlash 0
set_interface_assignment filter_alu_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment filter_alu_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment filter_alu_slave embeddedsw.configuration.isPrintableDevice 0

